#!/usr/bin/env python3
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

from harnessing.core.proactive_consistency_scanner import ConsistencyGap, Severity
from harnessing.core.subproject_health_monitor import HealthStatus, ProjectHealth, RiskLevel

_PROJECT_ROOT = Path(__file__).parent.parent.parent.parent


class AutoReportEngine:
    def __init__(self, project_root: Path | None = None) -> None:
        self.project_root = project_root or _PROJECT_ROOT

    def generate_report(
        self,
        consistency_gaps: list[ConsistencyGap],
        project_healths: list[ProjectHealth],
    ) -> str:
        now = datetime.now(timezone.utc).isoformat()
        lines: list[str] = []

        lines.append("# Harnessing Auto Report")
        lines.append("")
        lines.append(f"**Generated**: {now}")
        lines.append(f"**Project Root**: `{self.project_root}`")
        lines.append("")

        self._append_executive_summary(lines, consistency_gaps, project_healths)
        self._append_severity_section(lines, consistency_gaps, Severity.CRITICAL)
        self._append_severity_section(lines, consistency_gaps, Severity.HIGH)
        self._append_health_overview(lines, project_healths)
        self._append_stale_high_risk_details(lines, project_healths)
        self._append_recommended_actions(lines, consistency_gaps, project_healths)

        lines.append("---")
        lines.append("")
        lines.append("*Generated by AutoReportEngine*")

        return "\n".join(lines)

    def _append_executive_summary(
        self,
        lines: list[str],
        gaps: list[ConsistencyGap],
        healths: list[ProjectHealth],
    ) -> None:
        severity_counts: dict[str, int] = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
        for g in gaps:
            severity_counts[g.severity.value] += 1

        active = sum(1 for h in healths if h.status == HealthStatus.ACTIVE)
        stale = sum(1 for h in healths if h.status == HealthStatus.STALE)
        high_risk = sum(1 for h in healths if h.status == HealthStatus.HIGH_RISK)
        completed = sum(1 for h in healths if h.status == HealthStatus.COMPLETED)

        lines.append("## Executive Summary")
        lines.append("")
        lines.append(f"**Total Consistency Issues**: {len(gaps)}")
        lines.append(f"**Total Sub-Projects**: {len(healths)}")
        lines.append("")

        lines.append("### Issues by Severity")
        lines.append("")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
            lines.append(f"| {sev} | {severity_counts[sev]} |")
        lines.append("")

        lines.append("### Sub-Project Status Summary")
        lines.append("")
        lines.append("| Status | Count |")
        lines.append("|--------|-------|")
        lines.append(f"| 🟢 ACTIVE | {active} |")
        lines.append(f"| 🟡 STALE | {stale} |")
        lines.append(f"| 🔴 HIGH_RISK | {high_risk} |")
        lines.append(f"| ✅ COMPLETED | {completed} |")
        lines.append("")

    def _append_severity_section(
        self,
        lines: list[str],
        gaps: list[ConsistencyGap],
        severity: Severity,
    ) -> None:
        filtered = [g for g in gaps if g.severity == severity]
        if not filtered:
            return

        icon = {Severity.CRITICAL: "🔴", Severity.HIGH: "🟠"}.get(severity, "⚠️")
        lines.append(f"## {icon} {severity.value} Issues")
        lines.append("")

        for g in filtered:
            lines.append(self._format_gap(g))

    def _format_gap(self, gap: ConsistencyGap) -> str:
        parts: list[str] = []
        parts.append(f"### [{gap.severity.value}] {gap.gap_type or 'gap'}")
        parts.append("")
        parts.append(f"- **Description**: {gap.description}")
        parts.append(f"- **Source**: `{gap.source_file}`")
        parts.append(f"- **Target**: `{gap.target_file}`")
        parts.append(f"- **Suggested Fix**: {gap.suggested_fix}")
        if gap.details:
            detail_items = ", ".join(f"{k}={v}" for k, v in gap.details.items())
            parts.append(f"- **Details**: {detail_items}")
        parts.append("")
        return "\n".join(parts)

    def _append_health_overview(
        self,
        lines: list[str],
        healths: list[ProjectHealth],
    ) -> None:
        lines.append("## Sub-Project Health Overview")
        lines.append("")

        if not healths:
            lines.append("No sub-projects found.")
            lines.append("")
            return

        lines.append("| Project | Status | Last Updated | Risk Level | Tasks | Checklist |")
        lines.append("|---------|--------|--------------|------------|-------|-----------|")

        for h in healths:
            status_icon = self._status_icon(h.status)
            risk_icon = self._risk_icon(h.risk_level)
            updated = h.last_updated.strftime("%Y-%m-%d") if h.last_updated else "-"
            tasks = "✅" if h.has_tasks else "❌"
            checklist = "✅" if h.has_checklist else "❌"
            lines.append(
                f"| {h.name} | {status_icon} {h.status.value} | {updated} "
                f"| {risk_icon} {h.risk_level.value} | {tasks} | {checklist} |"
            )

        lines.append("")

    def _append_stale_high_risk_details(
        self,
        lines: list[str],
        healths: list[ProjectHealth],
    ) -> None:
        flagged = [h for h in healths if h.status in (HealthStatus.STALE, HealthStatus.HIGH_RISK)]
        if not flagged:
            return

        lines.append("## ⚠️ STALE / HIGH_RISK Projects")
        lines.append("")

        for h in flagged:
            lines.append(self._format_project(h))

    def _format_project(self, health: ProjectHealth) -> str:
        parts: list[str] = []
        icon = "🔴" if health.status == HealthStatus.HIGH_RISK else "🟡"
        parts.append(f"### {icon} {health.name}")
        parts.append("")
        parts.append(f"- **Status**: {health.status.value}")
        parts.append(f"- **Risk Level**: {health.risk_level.value}")
        if health.last_updated:
            days = (datetime.now() - health.last_updated).days
            parts.append(f"- **Last Updated**: {health.last_updated.strftime('%Y-%m-%d')} ({days} days ago)")
        else:
            parts.append("- **Last Updated**: Unknown")
        parts.append(f"- **Has tasks.md**: {'Yes' if health.has_tasks else 'No'}")
        parts.append(f"- **Has checklist.md**: {'Yes' if health.has_checklist else 'No'}")

        if health.pain_points:
            parts.append("")
            parts.append("**Pain Points**:")
            for pp in health.pain_points:
                parts.append(f"- {pp}")

        parts.append("")
        return "\n".join(parts)

    def _append_recommended_actions(
        self,
        lines: list[str],
        gaps: list[ConsistencyGap],
        healths: list[ProjectHealth],
    ) -> None:
        lines.append("## Recommended Actions")
        lines.append("")

        actions: list[tuple[int, str]] = []
        num = 1

        critical_gaps = [g for g in gaps if g.severity == Severity.CRITICAL]
        for g in critical_gaps:
            actions.append((1, f"{num}. 🔴 **[CRITICAL]** {g.description} — {g.suggested_fix}"))
            num += 1

        high_risk_projects = [h for h in healths if h.status == HealthStatus.HIGH_RISK]
        for h in high_risk_projects:
            actions.append((2, f"{num}. 🔴 **{h.name}** — Resolve CRITICAL/HIGH pain points immediately"))
            num += 1

        high_gaps = [g for g in gaps if g.severity == Severity.HIGH]
        for g in high_gaps:
            actions.append((3, f"{num}. 🟠 **[HIGH]** {g.description} — {g.suggested_fix}"))
            num += 1

        stale_projects = [h for h in healths if h.status == HealthStatus.STALE]
        for h in stale_projects:
            days = (datetime.now() - h.last_updated).days if h.last_updated else 0
            actions.append((4, f"{num}. 🟡 **{h.name}** — Stale for {days} days, review if still active"))
            num += 1

        no_tasks = [
            h for h in healths
            if not h.has_tasks and h.status in (HealthStatus.ACTIVE, HealthStatus.HIGH_RISK)
        ]
        for h in no_tasks:
            actions.append((5, f"{num}. 📋 **{h.name}** — Create tasks.md for progress tracking"))
            num += 1

        medium_gaps = [g for g in gaps if g.severity == Severity.MEDIUM]
        if medium_gaps:
            actions.append((6, f"{num}. ⚠️ Review {len(medium_gaps)} MEDIUM consistency gaps"))
            num += 1

        actions.sort(key=lambda a: a[0])

        if actions:
            for _, text in actions:
                lines.append(text)
        else:
            lines.append("All systems healthy. No immediate actions required.")

        lines.append("")

    def _status_icon(self, status: HealthStatus) -> str:
        icons = {
            HealthStatus.ACTIVE: "🟢",
            HealthStatus.STALE: "🟡",
            HealthStatus.HIGH_RISK: "🔴",
            HealthStatus.COMPLETED: "✅",
            HealthStatus.UNKNOWN: "⚪",
        }
        return icons.get(status, "⚪")

    def _risk_icon(self, risk: RiskLevel) -> str:
        icons = {
            RiskLevel.CRITICAL: "🔴",
            RiskLevel.HIGH: "🟠",
            RiskLevel.MEDIUM: "🟡",
            RiskLevel.LOW: "🟢",
            RiskLevel.NONE: "✅",
        }
        return icons.get(risk, "⚪")


def main() -> None:
    from harnessing.core.proactive_consistency_scanner import ProactiveConsistencyScanner
    from harnessing.core.subproject_health_monitor import SubProjectHealthMonitor

    root = _PROJECT_ROOT

    scanner = ProactiveConsistencyScanner(project_root=root)
    gaps = scanner.scan()

    monitor = SubProjectHealthMonitor(root)
    healths = monitor.scan()

    engine = AutoReportEngine(project_root=root)
    report = engine.generate_report(gaps, healths)
    print(report)

    critical = sum(1 for g in gaps if g.severity == Severity.CRITICAL)
    high_risk = sum(1 for h in healths if h.status == HealthStatus.HIGH_RISK)

    if critical > 0 or high_risk > 0:
        sys.exit(2)
    elif any(g.severity == Severity.HIGH for g in gaps):
        sys.exit(1)
    else:
        sys.exit(0)


if __name__ == "__main__":
    main()
